# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sgotipy.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsgotipy.proto\"y\n\x13StartSgotipyRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x12\n\ntoken_type\x18\x02 \x01(\t\x12\r\n\x05scope\x18\x03 \x01(\t\x12\x12\n\nexpires_in\x18\x04 \x01(\x05\x12\x15\n\rrefresh_token\x18\x05 \x01(\t\"\'\n\x14StartSgotipyResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x14\n\x12StopSgotipyRequest\"&\n\x13StopSgotipyResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x16\n\x14SgotipyStatusRequest\"\'\n\x15SgotipyStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xc6\x01\n\x07Sgotipy\x12=\n\x0cStartSgotipy\x12\x14.StartSgotipyRequest\x1a\x15.StartSgotipyResponse\"\x00\x12:\n\x0bStopSgotipy\x12\x13.StopSgotipyRequest\x1a\x14.StopSgotipyResponse\"\x00\x12@\n\rSgotipyStatus\x12\x15.SgotipyStatusRequest\x1a\x16.SgotipyStatusResponse\"\x00\x42\x10Z\x0e./grpc/sgotipyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sgotipy_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\016./grpc/sgotipy'
  _STARTSGOTIPYREQUEST._serialized_start=17
  _STARTSGOTIPYREQUEST._serialized_end=138
  _STARTSGOTIPYRESPONSE._serialized_start=140
  _STARTSGOTIPYRESPONSE._serialized_end=179
  _STOPSGOTIPYREQUEST._serialized_start=181
  _STOPSGOTIPYREQUEST._serialized_end=201
  _STOPSGOTIPYRESPONSE._serialized_start=203
  _STOPSGOTIPYRESPONSE._serialized_end=241
  _SGOTIPYSTATUSREQUEST._serialized_start=243
  _SGOTIPYSTATUSREQUEST._serialized_end=265
  _SGOTIPYSTATUSRESPONSE._serialized_start=267
  _SGOTIPYSTATUSRESPONSE._serialized_end=306
  _SGOTIPY._serialized_start=309
  _SGOTIPY._serialized_end=507
# @@protoc_insertion_point(module_scope)
