# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sgotify_pb2 as sgotify__pb2


class SgotifyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendSpotifyAuth = channel.unary_unary(
                '/Sgotify/SendSpotifyAuth',
                request_serializer=sgotify__pb2.SpotifyAuth.SerializeToString,
                response_deserializer=sgotify__pb2.SpotifyAuthReply.FromString,
                )


class SgotifyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendSpotifyAuth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SgotifyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendSpotifyAuth': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSpotifyAuth,
                    request_deserializer=sgotify__pb2.SpotifyAuth.FromString,
                    response_serializer=sgotify__pb2.SpotifyAuthReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Sgotify', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Sgotify(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendSpotifyAuth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Sgotify/SendSpotifyAuth',
            sgotify__pb2.SpotifyAuth.SerializeToString,
            sgotify__pb2.SpotifyAuthReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
